### ISSUE TITLE
question for alignment

### ISSUE THREAD

**Issue by Liumomo30** [lfangyu09/IR-Crack-detection#6]
Hello, thank you for sharing your data, you achieved a perfect match, how did you do the alignment, thanks for the reply!

**Comment by lfangyu09** [comment]
What do you mean by the alignment? Do you ask how to build the ground truth data?

**Comment by Liumomo30** [comment]
> What do you mean by the alignment? Do you ask how to build the ground truth data?对齐是什么意思？您问如何构建地面实况数据吗？

Thank you for your reply. I would like to build my own batch of data for infrared and visible image fusion, but due to equipment factors, there is an offset between the infrared image and the visible image, and I didn't find a suitable alignment algorithm to make the two images perfectly aligned, however, your data is perfectly aligned, and I would like to ask you how you did it!

**Comment by lfangyu09** [comment]
We also faced this issue. We tried to match them but we found there are no obvious patterns. What we did is to adjust infrared cameras when collecting images. But there are still a few gaps in a few fusion images. You could find this pattern in out IRT datasets:
https://zenodo.org/records/11638443
https://zenodo.org/records/11625865
https://zenodo.org/records/11625820.
